<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>63adffba-ec6b-4be0-9006-863c1bc303c2</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.27">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Serilog" Version="4.2.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.16" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
		<PackageReference Include="Scrutor" Version="4.2.2" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.27" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CoffeeCRM.Core\CoffeeCRM.Core.csproj" />
	  <ProjectReference Include="..\CoffeeCRM.Data\CoffeeCRM.Data.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\images\avatar\" />
	  <Folder Include="wwwroot\images\dish\" />
	</ItemGroup>

</Project>
